### ISSUE TITLE
Do a first pass at a transform API

### ISSUE THREAD

**Issue by ben-ng** [ben-ng/paq#10]
haven't settled on a final API yet, but the first step is to get _something_ working through the CLI, even if its clunky.

**Comment by joeybaker** [comment]
:+1: for being able to use browserify transforms … that would be a huge ecosystem boost out of the gate. Browserify plugins are harder though.

**Comment by ben-ng** [comment]
:white_check_mark: 47c0803b88501d799490822dda26d27dd0b7d724
