### ISSUE TITLE
Get hbsfy working

### ISSUE THREAD

**Issue by ben-ng** [ben-ng/paq#2]

**Comment by joeybaker** [comment]
*hbsfy

…because spelling is hard.

**Comment by ben-ng** [comment]
thanks :P

**Comment by ben-ng** [comment]
Working and [tested](https://github.com/ben-ng/paq/blob/master/paq-tests/main.mm#L328) as of 51f5f0d80a0be91f7e4f7cd11fc65925c19d0254
