### ISSUE TITLE
Get babelify/reactify working (oscar)

### ISSUE THREAD

**Issue by ben-ng** [ben-ng/paq#4]

**Comment by joeybaker** [comment]
Actually, just get babelify working. That includes jsx support. :)

**Comment by ben-ng** [comment]
oh neat

**Comment by jmorrell** [comment]
ha, I came here to make the same point :P

**Comment by ben-ng** [comment]
I'm clueless about react right now :)

**Comment by joeybaker** [comment]
Just noting… this should be added to the "works for getable" milestone too. We'll need it soon :)

**Comment by ben-ng** [comment]
Working and [tested](https://github.com/ben-ng/paq/blob/master/paq-tests/main.mm#L347) as of 51f5f0d80a0be91f7e4f7cd11fc65925c19d0254

Issue logged with babel: https://github.com/babel/babel/pull/1112
